### ISSUE TITLE
munin graphing of concurrent users vs named users

### ISSUE THREAD

**Issue by hvisage** [mendix/m2ee-tools#16]
Good day,

 I have a case were the named users are so much more than the normal concurrent users, that in the munin graphs, the named users are hiding the details of the concurrent user's usage graph, as shown in the attached graph.
 
![mxruntime_sessions_aquacheckweb-day](https://user-images.githubusercontent.com/11662665/30166799-b7b408ac-93e4-11e7-8927-d8eda5d1d7a9.png)

If I spend the time to fix/change for a pull request, is there any specific way I should split up these data? Is there a use for these together?

I would've liked to have the named users an AREA and then STACK the anonymous connections on top.

**Comment by knorrie** [comment]
There's a configuration switch that hides the total amount of users in the graph. You can use that if you're more interested in the actual amount of logged in users instead.

https://github.com/mendix/m2ee-tools/blob/master/examples/full-documented-m2ee.yaml#L344

Splitting the graphs into a graph with names user count and another graph with logged in users would make both of the values visible in a nicer way. However, this means that part of the fields need a new (plugin) name. The fact that we don't have control over the actual munin rrd files of the user, means that the user would have to manually rename the rrd files to match the new name, otherwise their history will be lost in the graph. Simply this is the reason it has not happened yet.

**Comment by hvisage** [comment]
Thanks, that helped ;)
